### PR TITLE
🚑  fix Android11 permission bug

### PR DESCRIPTION
**Pull request by dyy1993**
### Type of the change

* [ ] Feature
* [x] Bugfix
* [ ] Technical
* [ ] Documentation
* [ ] Other

### Description

The Android 11 permission is denied When Android add WRITE_EXTERNAL_STORAGE maxSdkVersion is 29. (User authorized)
#665

### CODE REVIEW

**Comment by AlexV525** [comment]
What if the `WRITE_EXTERNAL_STORAGE` is truly denied on the current device?

**Comment by AlexV525** [comment]
If we can't figure out what exactly the problem is, this PR is still having false positives when handling permissions.

Converting this to draft since we don't have a clear conclusion here.

**Comment by dyy1993** [comment]
> If we can't figure out what exactly the problem is, this PR is still having false positives when handling permissions.
> 
> Converting this to draft since we don't have a clear conclusion here.

We refer to permission_handler to reprocess the write permission on Android 11. [permission-handler pr](https://github.com/Baseflow/flutter-permission-handler/pull/526)
WechatIMG236

**Comment by AlexV525** [comment]
Again with https://github.com/fluttercandies/flutter_photo_manager/issues/665#issuecomment-1000770787, they're new recommended methods rather than required methods. You're indicating various scopes for your request. Please make them clear.

**Comment by AlexV525** [comment]
#675

**Pull request closed without merging**
