### PR TITLE
✨ Add locks to the image provider

### PR DESCRIPTION
**Pull request by AlexV525**
Resolves https://github.com/LeGoffMael/insta_assets_picker/issues/24.

### CODE REVIEW

**Comment by AlexV525** [comment]
@LeGoffMael Could you help test the fix?

**Comment by CaiJingLong** [comment]
This is an attempt to solve the concurrency problem of ImageProvider from the dart layer.
Android uses Glide to load thumbnails, and there are no network images, so there are no concurrency issues

iOS has icloud and PHAssetResource and caches them locally, so there will be some problems.
I plan to build a simple local caching natively on iOS to solve this problem in the future. Before that, we can try to use the code of this PR.

**Comment by LeGoffMael** [comment]
Hi @AlexV525, i will check it later tonight

**Comment by LeGoffMael** [comment]
I just tested using `insta_assets_picker` and it seems that the error is fixed !

I tried to load assets on my iPhone (from local and iCloud) multiple times and i could not reproduce the problem.
I restarted m phone, clean the project and delete the example app between each test (with and without the fix).

**Pull request merged**
