### PR TITLE
Add field playbackStyle to DarwinColumns for imporve filter IOS

### PR DESCRIPTION
**Pull request by Ic3Sandy**
Utilize this tool to enhance iOS filtering capabilities for images and videos, including support for GIFs.

docs: [playbackstyle](https://developer.apple.com/documentation/photokit/phasset/2909060-playbackstyle)

### CODE REVIEW

**Comment by AlexV525** [comment]
@Ic3Sandy Thanks for the new feature. Could you also add an example entry and docs to indicate how it can be used?

**Comment by Ic3Sandy** [comment]
### Sure!
Example: If I need to filter only GIF images, I can use SQL like this `CustomColumns.darwin.playbackStyle == 2`

(imageAnimated = 2) [imageanimated](https://developer.apple.com/documentation/photokit/phasset/playbackstyle/imageanimated)

**Comment by AlexV525** [comment]
What I mean is adding them into the code.

**Comment by Ic3Sandy** [comment]
I have added the example code and documentation as you requested.

**Comment by Ic3Sandy** [comment]
@AlexV525 If you have any corrections or additions you'd like me to make, feel free to let me know. I'm more than happy to help.

**Comment by AlexV525** [comment]
Please add the feature interactions in the example, so we can visually see how the feature works.

**Review by CaiJingLong — APPROVED** [review]

**Comment by CaiJingLong** [comment]
LGTM，thanks for PR.

**Pull request merged**
