### PR TITLE
Notify

### PR DESCRIPTION
**Pull request by bdlukaa**
#652 

*ONLY TESTED ON ANDROID*

### Before

```dart
PhotoManager.addChangeCallback(changeNotify);
PhotoManager.startChangeNotify();
```

```dart
PhotoManager.removeChangeCallback(changeNotify);
PhotoManager.stopChangeNotify();
```

### Now

```dart
PhotoManager.onChangeNotify.listen((NotifyChangeInfo info) {
  print(info);
});
```

### CODE REVIEW

**Review by AlexV525 — COMMENTED** [review]
I'm not fully reviewed this, but we should move on to iOS/macOS.

**Comment by bdlukaa** [comment]
@AlexV525 I don't have a macos to test if it'd go well. Any suggestions?

**Comment by AlexV525** [comment]
Drafting it, and I'll see if there is any chance to follow this up.

**Comment by AlexV525** [comment]
P.S. It'll be more acceptable if we hold the inner type as `MethodCall`, instead of some unverified abstraction, which allows the main idea of this PR to land first, then tweak them by covering all contents. Also, I would be pleased if new content is well explained and documented, making it easy to review.

**Pull request closed without merging**
